### ISSUE TITLE
chapter06의 requirements.txt 파일이 비어있습니다.

### ISSUE THREAD

**Issue by fakecan** [wikibook/practical-gan#14]

**Comment by wikibook** [comment]
안녕하세요. 위키북스입니다.

말씀하신 내용을 역자분께 전달했고, 원래 원서에서는 제공되지 않는 파일인데 역자가 파일을 만들어서 제공하겠다고 합니다.

6장용 requirements.txt 파일을 만들려면 설정을 바꿔가면서 테스트해봐야 해서 2주 정도 후에 업로드할 수 있다고 답변을 받았습니다.

참고 부탁드립니다. 감사합니다.
